import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import {NuqsAdapter} from 'nuqs/adapters/next'

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meet",
  description: "Generated by create next app",
  icons:{
    icon:"/logo.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <NuqsAdapter>
      <TRPCReactProvider>
      <html lang="en">
        <body className={`${inter.className}  antialiased`}>{children}</body>
      </html>
    </TRPCReactProvider>
  </NuqsAdapter>
  );
}
